version: "3.8"

services:
  app:
    build: .
    image:  php:8.1-apache
    container_name: pizzawebsite
    volumes:
      - C:/Users/User/Desktop/PHP/pizzaweb/web:/var/www/html
    depends_on:
      - mysql
    links:
      - mysql
    stdin_open: true
    tty: true
    ports:
      - "8000:80"
  mysql:
    image: mysql:8.0
    container_name: pizzabd
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "MYSQL_ROOT_PASSWORD"
      MYSQL_DATABASE: "PIZZAWEBSITE"
      MYSQL_USER: "MYSQL_USER"
      MYSQL_PASSWORD: "MYSQL_PASSWORD"
    ports:
      - "3306:3306"